### ISSUE TITLE
measured boot scenario fails with unexpected ('PCRIndex', 'EventType') combination

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1393]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version:  RHEL-9.2 or CentOS Stream 9 on a host, RHEL-9.2 or C9S on the virtual guest
 * Processor architecture: x86_64
 * TPM Manufacturer: RPM dev emualted through qemu/kvm/swtpm
 * Keylime version: current upstream

# Description 
I started observing failures in the measured boot scenario in a virtual system with RHEL-9.2. Previously, it was working which pointed my attention to the host. It seems that some qemu/kvm/* update introduced a change that gets propagated to the guest.

On the guest, the attestation fails due to key derivation error, in the verifier log there is an error message ending with
```
... has unexpected ('PCRIndex', 'EventType') combination (1, 'EV_PLATFORM_CONFIG_FLAGS')
```
and in the `binary_bios_measurements` I can see 4 records like this:
```
 EventNum: 10
  PCRIndex: 1
  EventType: EV_PLATFORM_CONFIG_FLAGS
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "9b00be8f1e820662b4067bbf901243bc4c7bd659da70804bc4c822553b97234c"
  EventSize: 9
  Event: "414350492044415441"
```
It seems that this EventType is unknown to keylime `create_mb_refstate` script  or the verifier.
`create_mb_refstate` script alone didn't report any problem.

## Expected behavior vs. actual behavior 
agent on a measured boot system does not pass attestation.

## Steps to reproduce problem
1. on a host system with RHEL-9.2 or C9S create a virtual guest with secure boot enabled and create a mb policy using the binary_bios_measurements from the guest.
